### ISSUE TITLE
Request : Export packages

### ISSUE THREAD

**Issue by jurepolutnik** [joakimkistowski/LIMBO#13]
Is it possible to open packages in editor plugin, so the classes could
be used also externally? We are integrating DLIM into the CloudScale Environment, 
and we would like to customize DLIM wizard a bit.

**Comment by joakimkistowski** [comment]
wizards and views pacakges are now exported. Source version on GitHub is already up to date. Expect release of the newest binary using this feature via our update site some time next week.

**Comment by jurepolutnik** [comment]
thanks.
